
version: '3.9'

services:
  tika-server:
    image: apache/tika:latest
    container_name: tika-server
    ports:
      - "9998:9998"
    command: --enableUnsecureFeatures --config=/tika-config.xml
    volumes:
      - ./tika-config.xml:/tika-config.xml
    networks:
      - tika-net

  mongo:
    image: mongo:7.0
    container_name: tika-mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - tika-net

  mongo-express:
    image: mongo-express
    container_name: tika-mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - tika-net

  ui:
    build: ./ui
    container_name: tika-ui
    ports:
      - "5000:5000"
    environment:
      - TIKA_SERVER_URL=http://tika-server:9998
      - MONGO_URL=mongodb://mongo:27017/tika_results
    depends_on:
      - tika-server
      - mongo
    networks:
      - tika-net

networks:
  tika-net:
    driver: bridge
